#include "System.h"

void SystemInit168MHZ(void)
{
	RCC->CR |= RCC_CR_HSEON;
	
	RCC->PLLCFGR  = 0;
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLM_2;																							//(0b000100) 		- PLLM (/4)
	RCC->PLLCFGR |= (RCC_PLLCFGR_PLLN_3 | RCC_PLLCFGR_PLLN_5 | RCC_PLLCFGR_PLLN_7);	//(0b010101000) - PLLN (*168)
	RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLLP_0 | RCC_PLLCFGR_PLLP_1);											//(0b00) 				- PLLP (/2)
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
	RCC->CR |= RCC_CR_PLLON;
	//FLASH->ACR |= FLASH_ACR_LATENCY_1WS;
	FLASH->ACR |= FLASH_ACR_LATENCY_7WS;
	RCC->CFGR &= ~(RCC_CFGR_HPRE_0 | RCC_CFGR_HPRE_1 | RCC_CFGR_HPRE_2 | RCC_CFGR_HPRE_3);	//(0b0000)	- HPRE  (/1)
	RCC->CFGR |= (RCC_CFGR_PPRE1_0 | RCC_CFGR_PPRE1_2);																			//(0b101)		- PPRE1 (/4)
	RCC->CFGR |= (RCC_CFGR_PPRE2_2);																												//(0b101)		- PPRE2 (/2)
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	RCC->CR &= ~RCC_CR_HSION;	
	
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
//	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
//	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
//	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
//	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;	
}
